#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/builder-nixpacks/internal-functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-builder-nixpacks-builder-build() {
  declare desc="builder-nixpacks builder-build plugin trigger"
  declare trigger="builder-build"
  declare BUILDER_TYPE="$1" APP="$2" SOURCECODE_WORK_DIR="$3"

  if [[ "$BUILDER_TYPE" != "nixpacks" ]]; then
    return
  fi

  dokku_log_info1 "Building $APP from nixpacks"

  if ! command -v "nixpacks" &>/dev/null; then
    dokku_log_fail "Missing nixpacks, install it"
  fi

  local IMAGE=$(get_app_image_name "$APP")

  pushd "$SOURCECODE_WORK_DIR" &>/dev/null

  plugn trigger pre-build "$BUILDER_TYPE" "$APP" "$SOURCECODE_WORK_DIR"

  no_cache="$(fn-builder-nixpacks-computed-no-cache "$APP")"
  NIXPACKS_ARGS=""
  if [[ "$no_cache" == "true" ]]; then
    NIXPACKS_ARGS="$NIXPACKS_ARGS --no-cache"
  fi

  ENV_ARGS=($(config_export app "$APP" --format key-list --merged))
  eval "$(config_export app "$APP" --merged)"

  if [[ -f "$SOURCECODE_WORK_DIR/Procfile" ]]; then
    if procfile-util exists --process-type release; then
      procfile-util delete --process-type release
    fi
  fi

  # shellcheck disable=SC2086
  nixpacks build --label dokku org.label-schema.schema-version=1.0 org.label-schema.vendor=dokku com.dokku.image-stage=build com.dokku.builder-type=nixpacks "com.dokku.app-name=$APP" $NIXPACKS_ARGS --env "${ENV_ARGS[@]}" --name "$IMAGE" "$SOURCECODE_WORK_DIR"

  if ! suppress_output "$DOCKER_BIN" image build $DOKKU_GLOBAL_BUILD_ARGS -f "$PLUGIN_AVAILABLE_PATH/builder-nixpacks/dockerfiles/builder-build.Dockerfile" --build-arg APP_IMAGE="$IMAGE" -t "$IMAGE" "$TMP_WORK_DIR"; then
    dokku_log_warn "Failure injecting docker labels and custom entrypoint on image"
    return 1
  fi

  plugn trigger post-build "$BUILDER_TYPE" "$APP" "$SOURCECODE_WORK_DIR"
  popd &>/dev/null || pushd "/tmp" >/dev/null
}

trigger-builder-nixpacks-builder-build "$@"
